name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  UpdateReleaseDraft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PUBLISH_SECRETS }}
